Error occurred at 2023-9-5 16:41:52 
 Error: Error: Unknown column 'userReported.muted' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:19:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- Error occurred at 2023-9-5 19:5:13 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'userAuthor.name as authorName, 
                    userReported.name as reporte' at line 3
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:20:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-6 14:29:51 
 Error: Answer id cannot be undefined
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at AnswerController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\AnswerController.ts:26:21)
    at Generator.next (<anonymous>)
    at C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\AnswerController.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\AnswerController.ts:4:12)
    at AnswerController.saveAnswer (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\AnswerController.ts:22:16)
    at C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\Routes.ts:53:43
    at Layer.handle [as handle_request] (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\node_modules\express\lib\router\route.js:144:13) 
 ------------------- 
Error occurred at 2023-9-6 14:49:18 
 Error: Answer id cannot be undefined
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at AnswerController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\AnswerController.ts:25:21)
    at Generator.next (<anonymous>)
    at C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\AnswerController.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\AnswerController.ts:4:12)
    at AnswerController.saveAnswer (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\AnswerController.ts:22:16)
    at C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\Routes.ts:53:43
    at Layer.handle [as handle_request] (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\node_modules\express\lib\router\route.js:144:13) 
 ------------------- 
Error occurred at 2023-9-11 15:13:23 
 Error: TypeError: Cannot destructure property 'muted' of 'reported' as it is undefined.
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:48:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-11 15:13:48 
 Error: TypeError: Cannot destructure property 'muted' of 'reported' as it is undefined.
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:48:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-11 15:14:11 
 Error: TypeError: Cannot destructure property 'muted' of 'reported' as it is undefined.
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:48:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-11 15:14:23 
 Error: TypeError: Cannot destructure property 'muted' of 'reported' as it is undefined.
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:48:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-11 15:14:44 
 Error: TypeError: Cannot destructure property 'muted' of 'reported' as it is undefined.
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:48:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-11 15:15:20 
 Error: TypeError: Cannot destructure property 'mutedTime' of 'reported' as it is undefined.
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:48:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-11 15:15:42 
 Error: TypeError: Cannot destructure property 'mutedTime' of 'reported' as it is undefined.
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:48:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-11 15:16:10 
 Error: TypeError: Cannot destructure property 'mutedTime' of 'reported' as it is undefined.
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:48:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-11 15:16:21 
 Error: TypeError: Cannot destructure property 'mutedTime' of 'reported' as it is undefined.
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:48:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-13 15:58:20 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM 
                    reports, 
                    users userAuthor, 
     ' at line 5
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:20:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-13 15:58:23 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM 
                    reports, 
                    users userAuthor, 
     ' at line 5
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:20:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-13 15:58:39 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 
                    reports.type = 'comment'
                    AND user' at line 9
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:20:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-13 15:58:41 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE 
                    reports.type = 'comment'
                    AND user' at line 9
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:20:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-27 14:8:30 
 Error: Error: Cannot add or update a child row: a foreign key constraint fails (`news`.`answers`, CONSTRAINT `answers_ibfk_2` FOREIGN KEY (`comment_id`) REFERENCES `comments` (`id`) ON DELETE CASCADE)
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at AnswerController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\AnswerController.ts:25:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\AnswerController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-27 14:40:57 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 3
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-27 14:42:20 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 3
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-27 14:42:40 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 3
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-27 15:23:59 
 Error: Error: Unknown column 'silencedTimes' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-27 15:25:5 
 Error: Error: Unknown column 'time_silenced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-27 15:30:42 
 Error: Error: Unknown column 'times_silnced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-27 15:45:42 
 Error: Error: Unknown column 'times_silnced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:15:1 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:15:29 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:15:42 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:17:39 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:17:52 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:18:21 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:18:32 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:18:40 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:23:48 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:23:55 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:24:28 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:24:39 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:25:6 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-28 9:25:15 
 Error: Error: Unknown column 'times_sienced' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at ReportController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:54:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\ReportController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-29 18:55:26 
 Error: Error: Table 'news.user' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:76:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-29 18:55:48 
 Error: Error: Table 'news.user' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:76:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-29 18:56:14 
 Error: Error: Table 'news.user' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:76:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-29 18:58:37 
 Error: Error: Table 'news.user' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:76:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-29 18:59:3 
 Error: Error: Table 'news.user' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:76:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-29 18:59:31 
 Error: Error: Table 'news.user' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:76:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-29 19:59:16 
 Error: Error: Table 'news.user' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:76:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-29 19:59:34 
 Error: Error: Table 'news.user' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:76:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-29 20:2:30 
 Error: Error: Table 'news.user' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:76:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-29 20:2:34 
 Error: Error: Table 'news.user' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:76:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-29 20:3:41 
 Error: Error: Table 'news.user' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:76:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-9-29 20:9:34 
 Error: Error: Table 'news.user' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:76:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-2 15:43:5 
 Error: Error: Table 'news.user' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:76:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-3 14:45:0 
 Error: Error: Unknown column 'NaN' in 'where clause'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at CommentController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CommentController.ts:41:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CommentController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-3 14:45:24 
 Error: Error: Unknown column 'NaN' in 'where clause'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at CommentController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CommentController.ts:41:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CommentController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-16 14:7:43 
 Error: Error: Truncated incorrect DOUBLE value: 'undefined'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:104:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-16 14:8:0 
 Error: Error: Truncated incorrect DOUBLE value: 'undefined'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:104:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-17 12:55:49 
 Error: TypeError: Cannot read properties of undefined (reading 'parentId')
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at CategoryController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CategoryController.ts:48:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CategoryController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-17 12:56:1 
 Error: TypeError: Cannot read properties of undefined (reading 'parentId')
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at CategoryController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CategoryController.ts:48:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CategoryController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-17 14:58:48 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-24' at line 7
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:117:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-17 14:59:0 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-24' at line 7
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:118:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-17 15:0:1 
 Error: Error: Table 'news.new' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:118:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-17 15:0:19 
 Error: Error: Table 'news.new' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:118:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-17 15:0:31 
 Error: Error: Table 'news.new' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:118:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-17 16:38:8 
 Error: Error: Truncated incorrect DOUBLE value: 'undefined'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:118:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-17 16:39:21 
 Error: Error: Truncated incorrect DOUBLE value: 'undefined'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:118:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-18 14:28:25 
 Error: Error: Unknown column 'news.desciption' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:118:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-18 14:28:33 
 Error: Error: Unknown column 'news.desciption' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:118:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-18 14:28:50 
 Error: Error: Unknown column 'news.desciption' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:118:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-18 14:28:58 
 Error: Error: Unknown column 'news.desciption' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:118:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-18 14:29:32 
 Error: Error: Unknown column 'news.desciption' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:118:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-18 14:31:51 
 Error: Error: Unknown column 'news.desciption' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:118:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-20 15:8:15 
 Error: Error: connect ECONNREFUSED ::1:3306
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at CategoryController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CategoryController.ts:48:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CategoryController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-20 15:8:15 
 Error: Error: connect ECONNREFUSED ::1:3306
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:38:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-20 15:8:15 
 Error: Error: connect ECONNREFUSED ::1:3306
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at CategoryController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CategoryController.ts:48:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CategoryController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-10-20 15:8:15 
 Error: Error: connect ECONNREFUSED ::1:3306
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:38:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\UserController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-13 20:43:23 
 Error: Error: Truncated incorrect DOUBLE value: 'Nova versão do Scania bicudo está quase pronta na Noruega'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-13 20:43:23 
 Error: Error: Truncated incorrect DOUBLE value: 'Nova versão do Scania bicudo está quase pronta na Noruega'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-13 20:43:24 
 Error: Error: Truncated incorrect DOUBLE value: 'Nova versão do Scania bicudo está quase pronta na Noruega'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-13 20:43:24 
 Error: Error: Truncated incorrect DOUBLE value: 'Nova versão do Scania bicudo está quase pronta na Noruega'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-13 20:43:40 
 Error: Error: Truncated incorrect DOUBLE value: 'Nova versão do Scania bicudo está quase pronta na Noruega'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:117:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-13 20:43:40 
 Error: Error: Truncated incorrect DOUBLE value: 'Nova versão do Scania bicudo está quase pronta na Noruega'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:117:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-17 16:28:41 
 Error: Error: connect ECONNREFUSED ::1:3306
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-17 16:28:42 
 Error: Error: connect ECONNREFUSED ::1:3306
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-17 17:6:15 
 Error: Error: Unknown column 'NaN' in 'where clause'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at CommentController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CommentController.ts:41:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CommentController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-17 17:7:15 
 Error: Error: Unknown column 'NaN' in 'where clause'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at CommentController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CommentController.ts:41:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\CommentController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-17 17:8:23 
 Error: Error: Column 'id' in field list is ambiguous
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-17 17:8:24 
 Error: Error: Column 'id' in field list is ambiguous
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-17 17:8:24 
 Error: Error: Column 'id' in field list is ambiguous
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-17 17:8:25 
 Error: Error: Column 'id' in field list is ambiguous
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-17 17:8:34 
 Error: Error: Column 'id' in field list is ambiguous
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-17 17:8:34 
 Error: Error: Column 'id' in field list is ambiguous
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\restAPI\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-20 16:21:34 
 Error: TypeError: Cannot read properties of undefined (reading 'id')
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:30:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-20 16:22:6 
 Error: TypeError: Cannot read properties of undefined (reading 'id')
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:30:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-20 16:43:29 
 Error: Error: ID is undefined
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:30:21)
    at Generator.next (<anonymous>)
    at C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:4:12)
    at NewsController.save (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:22:16)
    at C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\Routes.ts:32:41
    at Layer.handle [as handle_request] (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\node_modules\express\lib\router\route.js:144:13) 
 ------------------- 
Error occurred at 2023-11-20 18:56:26 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id as categoryId
                FROM 
                    news, category
     ' at line 3
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-20 18:56:28 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id as categoryId
                FROM 
                    news, category
     ' at line 3
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-20 18:56:29 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id as categoryId
                FROM 
                    news, category
     ' at line 3
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-20 18:56:30 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id as categoryId
                FROM 
                    news, category
     ' at line 3
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-21 9:32:41 
 Error: Error: connect ECONNREFUSED ::1:3306
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:116:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-21 10:24:58 
 Error: Error: Table 'news.new' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:30:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-21 10:26:33 
 Error: Error: Table 'news.new' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:30:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-21 10:27:47 
 Error: Error: Table 'news.new' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:30:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-21 10:28:10 
 Error: Error: Table 'news.new' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:30:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-21 10:28:33 
 Error: Error: Table 'news.new' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:30:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\NewsController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-21 11:21:6 
 Error: Error: Table 'news.categoy' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at CategoryController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CategoryController.ts:50:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CategoryController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-21 15:51:54 
 Error: Error: Table 'news.categor' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at CategoryController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CategoryController.ts:29:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CategoryController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-21 15:52:28 
 Error: Error: Table 'news.categor' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at CategoryController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CategoryController.ts:29:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CategoryController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-21 15:53:20 
 Error: Error: Table 'news.categor' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at CategoryController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CategoryController.ts:29:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CategoryController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-21 15:53:38 
 Error: Error: Table 'news.categor' doesn't exist
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at CategoryController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CategoryController.ts:29:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CategoryController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-22 11:14:56 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'answers.datePosted,
                    answers.agree_count as agreeCount, answe' at line 4
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at CommentController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:41:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-22 11:15:3 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'answers.datePosted,
                    answers.agree_count as agreeCount, answe' at line 4
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at CommentController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:41:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-22 11:15:8 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'answers.datePosted,
                    answers.agree_count as agreeCount, answe' at line 4
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at CommentController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:41:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-22 11:15:25 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'answers.datePosted,
                    answers.agree_count as agreeCount, answe' at line 4
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at CommentController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:41:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-22 11:15:48 
 Error: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'author
                WHERE comment_id = (SELECT comment_id FROM news WHERE id ' at line 8
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at CommentController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:41:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-22 11:16:6 
 Error: Error: Unknown column 'answers.datePosted' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at CommentController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:41:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-22 11:16:8 
 Error: Error: Unknown column 'answers.datePosted' in 'field list'
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at CommentController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:41:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\CommentController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 14:7:31 
 Error: Error: connect ECONNREFUSED ::1:3306
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\build\src\model\utils\LogError.js:9:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\build\src\controller\NewsController.js:120:40)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\build\src\controller\NewsController.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 14:7:31 
 Error: Error: connect ECONNREFUSED ::1:3306
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\build\src\model\utils\LogError.js:9:17)
    at CategoryController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\build\src\controller\CategoryController.js:63:40)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\build\src\controller\CategoryController.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 14:7:31 
 Error: Error: connect ECONNREFUSED ::1:3306
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\build\src\model\utils\LogError.js:9:17)
    at UserController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\build\src\controller\UserController.js:47:40)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\build\src\controller\UserController.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 14:7:33 
 Error: Error: connect ECONNREFUSED ::1:3306
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\build\src\model\utils\LogError.js:9:17)
    at NewsController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\build\src\controller\NewsController.js:120:40)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\build\src\controller\NewsController.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 14:27:39 
 Error: Error: Column count doesn't match value count at row 1
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at ReactionController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:47:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 14:29:9 
 Error: Error: Column count doesn't match value count at row 1
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at ReactionController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:47:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 14:30:12 
 Error: Error: Cannot add or update a child row: a foreign key constraint fails (`news`.`user_notification`, CONSTRAINT `user_notification_ibfk_3` FOREIGN KEY (`news_origen`) REFERENCES `news` (`id`))
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at ReactionController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:47:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 14:33:25 
 Error: Error: Cannot add or update a child row: a foreign key constraint fails (`news`.`user_notification`, CONSTRAINT `user_notification_ibfk_3` FOREIGN KEY (`news_origen`) REFERENCES `news` (`id`))
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at ReactionController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:47:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 14:33:59 
 Error: Error: Cannot add or update a child row: a foreign key constraint fails (`news`.`user_notification`, CONSTRAINT `user_notification_ibfk_3` FOREIGN KEY (`news_origen`) REFERENCES `news` (`id`))
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at ReactionController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:47:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 14:35:55 
 Error: Error: Cannot add or update a child row: a foreign key constraint fails (`news`.`user_notification`, CONSTRAINT `user_notification_ibfk_3` FOREIGN KEY (`news_origen`) REFERENCES `news` (`id`))
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at ReactionController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:47:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 14:36:24 
 Error: Error: Cannot add or update a child row: a foreign key constraint fails (`news`.`user_notification`, CONSTRAINT `user_notification_ibfk_3` FOREIGN KEY (`news_origen`) REFERENCES `news` (`id`))
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at ReactionController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:47:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 14:37:33 
 Error: Error: Cannot add or update a child row: a foreign key constraint fails (`news`.`user_notification`, CONSTRAINT `user_notification_ibfk_3` FOREIGN KEY (`news_origen`) REFERENCES `news` (`id`))
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at ReactionController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:47:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\ReactionController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 17:1:14 
 Error: Error: Column count doesn't match value count at row 1
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at AnswerController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\AnswerController.ts:30:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\AnswerController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
Error occurred at 2023-11-29 17:1:33 
 Error: Error: Column count doesn't match value count at row 1
    at LogError (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\model\utils\LogError.ts:5:17)
    at AnswerController.<anonymous> (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\AnswerController.ts:30:21)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\joseh\OneDrive\Documentos\Programming\Own\noticias\web_service\src\controller\AnswerController.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
 ------------------- 
